<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rememberUn</name>
   <tag></tag>
   <elementGuidId>396715e5-5aa4-436b-9ea9-e30d4af7366e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberUn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberUn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1efc530-c805-4a0c-9123-9ce283301462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3254466b-b603-4cf0-b1e2-4b13c56ae08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r4 fl mr8</value>
      <webElementGuid>987b971a-9f0b-42df-87bf-d48888dacaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberUn</value>
      <webElementGuid>b3cfab6a-f15b-430c-9504-6f69811021e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberUn</value>
      <webElementGuid>b60e9d88-382a-4424-ac46-8342ed20a9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberUn&quot;)</value>
      <webElementGuid>376b1556-7bca-4205-bbdf-938ea7f7a174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberUn']</value>
      <webElementGuid>5dfcf25a-c45f-4e57-abdc-1ddb138526a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[4]/input</value>
      <webElementGuid>9bf2f6d6-8339-4f10-b06e-098b22e56753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/input</value>
      <webElementGuid>f991792a-6140-4002-9db6-e4b99c395ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'rememberUn' and @name = 'rememberUn']</value>
      <webElementGuid>d777cb25-b752-4c65-9373-b52b6266e258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
