<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown</name>
   <tag></tag>
   <elementGuidId>61bddd62-9e30-48e9-8318-584a79e20ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='validationCustom04']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#validationCustom04</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a813d03-eafe-464d-84ef-bc0d17bdadc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>e55bbd2e-fe39-404a-880d-6da5e4525210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCustom04</value>
      <webElementGuid>f1a6be51-9ddb-4bc1-8408-4a718cfb3f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment</value>
      <webElementGuid>19502d0e-8d96-4223-b21d-fb6d83ab81e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Choose...
                                cash on delivery 
                                card

                            </value>
      <webElementGuid>5e06b169-bdf0-4447-adda-77c65881e199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;validationCustom04&quot;)</value>
      <webElementGuid>bf9aa014-9d13-4e48-879f-d09578085a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='validationCustom04']</value>
      <webElementGuid>a65556f0-9131-4c9f-9c04-82145ec1802a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e08cb47a-7222-49f8-9b28-4ae2bbe7f1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'validationCustom04' and @name = 'payment' and (text() = '
                                Choose...
                                cash on delivery 
                                card

                            ' or . = '
                                Choose...
                                cash on delivery 
                                card

                            ')]</value>
      <webElementGuid>79fb01af-14a6-4f5d-87a9-38120fd5bc89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
