<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickupdate</name>
   <tag></tag>
   <elementGuidId>fac94055-8cc2-4b8d-ae94-cb1d94c2e83c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='validationCustom05'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec7229b-c779-4802-a168-2b78376d96f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>f013fbf0-f5a8-4c92-b71d-38dd3d3551b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b690fccc-61a1-4b9a-8ffc-3ff96eda75e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>validationCustom05</value>
      <webElementGuid>a398910c-0dfb-412e-87ce-55a018482616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickupdate</value>
      <webElementGuid>b5a1ab89-e407-4815-bb44-148519866426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;d-flex flex-column min-vh-100&quot;]/main[@class=&quot;flex-shrink-0 py-3&quot;]/div[@class=&quot;page-layout&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;card-body&quot;]/form[@class=&quot;row g-3 needs-validation&quot;]/div[@class=&quot;col-md-6&quot;]/input[@id=&quot;validationCustom05&quot;]</value>
      <webElementGuid>abe61479-e51e-4fb1-99fb-92699b45c616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='validationCustom05'])[2]</value>
      <webElementGuid>054bfd1d-c9ee-43bb-9c49-b86d9a1c03fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ed122293-65c0-4b2a-ab32-6388f52853cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'validationCustom05' and @name = 'pickupdate']</value>
      <webElementGuid>8f3999f8-acf2-42b9-9593-227594823b49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
