<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send</name>
   <tag></tag>
   <elementGuidId>5bfc2951-e542-4fe4-aaa7-a1ae84835103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='1319:0']/div/div[3]/div/div/div[2]/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba1e0c43-15ee-4d99-9b8e-48ad19a36423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>6c1b6431-3f40-45a6-8da5-9b4fcc5fa55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> label bBody</value>
      <webElementGuid>915221a4-8cfe-42d2-8d91-6aa80a7bb340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1957:0</value>
      <webElementGuid>ee1c6ba2-ca66-48c8-b61b-435c6f6ed988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>8a76b8e9-12e9-49a7-9530-daefc037ce8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1319:0&quot;)/div[@class=&quot;testid__publisher-quick-action-collapser  forcePublisherQuickActionCollapser&quot;]/div[3]/div[@class=&quot;forceChatterPublisherPresentationDesktop forceChatterPublisherQuickAction supportPublisherQuickSendEmail&quot;]/div[@class=&quot;container notNeedOauth activeState&quot;]/div[@class=&quot;slds-grid bottomBar&quot;]/div[@class=&quot;bottomBarRight slds-col--bump-left&quot;]/button[@class=&quot;slds-button slds-button--brand cuf-publisherShareButton MEDIUM send uiButton&quot;]/span[@class=&quot;label bBody&quot;]</value>
      <webElementGuid>78961987-f93c-45d9-9dd2-9174d6d70b05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='1319:0']/div/div[3]/div/div/div[2]/div[2]/button/span</value>
      <webElementGuid>340ffaed-a6a8-4d92-a079-3b8f9cf2924a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span</value>
      <webElementGuid>dc4e2fe9-c540-4869-a147-9311345a3fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>096d0b0d-b519-4af6-9353-8b7500d4156e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
