<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickMeButton1</name>
   <tag></tag>
   <elementGuidId>e43f1021-7baa-45a3-86cb-8dad0cf66f37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='generateConfirmBox()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alertBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60a76226-4b5d-40f8-b8e4-d1b9090072af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertBox</value>
      <webElementGuid>a3779086-c7db-4fcf-92c3-1ec4f27e3f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>alertFunction()</value>
      <webElementGuid>57b97f98-3c26-4b65-b2b6-a466b89ffe0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click me</value>
      <webElementGuid>8d91e757-fbaa-4182-a7ca-ad37fe672d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertBox&quot;)</value>
      <webElementGuid>7f5bf1e2-ee43-4282-b481-115959921c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='alertBox']</value>
      <webElementGuid>65b239ea-a0f0-48a9-98c8-237229215a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-2252040019981508971']/div/div/button</value>
      <webElementGuid>beb3bada-dea8-4c6e-ba93-d5422b24c9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>021ecf89-b6d2-4f03-bbef-84093b445cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'alertBox' and (text() = 'Click me' or . = 'Click me')]</value>
      <webElementGuid>99d8d066-091f-462c-bba3-83172e2112f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
